version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - 3000:3000
  
  metabase:
    image: metabase/metabase
    ports:
      - 3002:3000
    env_file:
       - metabase/config/mongo_exemple.env
    depends_on:
      - mongo

   
