
name: deploy

on:
  push:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cópiando dados da master
      uses: actions/checkout@v2

    - name: Instalando python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Atualizando e instalando Poetry e suas dependências
      run: python -m pip install poetry

    - name: Instalando dependencias
      run: |
        poetry install

    - name: Instalando lint
      run: |
        pip install pylint
        pylint src
      continue-on-error: true

    - name: Executar testes unitários
      run: poetry run pytest --cov 

    - name: Build pacotes de dependencias do poetry
      run: poetry build -v

    - name: Publicação do trabalho e documentação
      run: |
        poetry config pypi-token.pypi ${{secrets.TOKEN_PYPI}} && poetry version ${{secrets.VERSION}} && poetry build && poetry publish
